package com.simcity.power;

public enum BuildingsEnum {
    HOUSE,
    MINE_COAL,
    MINE_URANIUM,
    MINE_OIL,
    ELECTRIC_GENERATOR_COAL,
    ELECTRIC_GENERATOR_URANIUM,
    ELECTRIC_GENERATOR_OIL,
    ELECTRIC_GENERATOR_WIND,
    ELECTRIC_GENERATOR_SOLAR,
    ELECTRIC_GENERATOR_WATER,
    ELECTRIC_GENERATOR_CREATIVE // for debugging
}
